apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # variáveis de conexão DB (pode vir de Secret/ConfigMap depois)
        - name: DB_HOST
          value: "10.0.20.77"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "webappdb"
        - name: DB_USER
          value: "admin"
		lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  cat > /usr/share/nginx/html/index.html << EOF
                  <!DOCTYPE html>
                  <html lang="pt-BR">
                  <head>
                    <meta charset="UTF-8">
                    <title>App Rodando no Pod</title>
                    <style>
                      body {
                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                        background: linear-gradient(to bottom, #0a1a2f, #000000);
                        color: #ecf0f1;
                        margin: 0;
                        padding: 0;
                        text-align: center;
                      }
                      .container {
                        max-width: 800px;
                        margin: 50px auto;
                        padding: 20px;
                        background: rgba(255,255,255,0.05);
                        border-radius: 12px;
                        box-shadow: 0 4px 12px rgba(0,0,0,0.5);
                      }
                      h1 {
                        color: #ffffff;
                        margin-bottom: 15px;
                        font-size: 2em;
                        text-transform: uppercase;
                        letter-spacing: 1px;
                      }
                      .pod-name {
                        font-size: 1.5em;
                        color: #ff6600; /* cor laranja estilo foguete */
                        font-weight: bold;
                        margin: 10px 0;
                      }
                      .info, .db {
                        margin: 6px 0;
                        font-size: 1em;
                        color: #bdc3c7;
                      }
                      .db b {
                        color: #ffcc66;
                      }
                      .timestamp {
                        font-size: 0.9em;
                        color: #95a5a6;
                        margin-top: 25px;
                      }
                    </style>
                  </head>
                  <body>
                    <div class="container">
                      <h1>🚀 App Rodando no Pod</h1>
                      <p class="pod-name">$POD_NAME</p>
                      <p class="info"><b>IP do Pod:</b> $POD_IP</p>
                      <p class="info"><b>Namespace:</b> $NAMESPACE</p>
                      <p class="info"><b>Worker Node:</b> $NODE_NAME</p>
                      <hr/>
                      <p class="db"><b>DB Host:</b> $DB_HOST</p>
                      <p class="db"><b>DB Port:</b> $DB_PORT</p>
                      <p class="db"><b>DB Name:</b> $DB_NAME</p>
                      <p class="db"><b>DB User:</b> $DB_USER</p>
                      <p class="timestamp">Página gerada em $(date)</p>
                    </div>
                  </body>
                  </html>
                  EOF
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

